package in.rbihub.entity;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.persistence.*;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.sql.Timestamp;
import java.util.UUID;

@Entity
@Data
@EqualsAndHashCode(callSuper = false)
@Table(name = "lender_loan_record")
public class LenderLoanRecordEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private UUID id;  // Loan ID

    private String lenderName;  // Bank name
    private String loanType;  // Loan type

    private Double loanDisbursedAmount;  // Disbursed amount as a number -change to sanction

    // Newly added fields
    private String district;  // District
    private String state;  // State
    private String branchCode;  // Branch code
    private String pincode;  // Pincode
    private String ifscCode;  // IFSC code
    private String gender;  // Gender (M/F/T)

    private Timestamp applicationStartTimestamp;  // Start Timestamp
    private Timestamp loanSanctionTimestamp;  // Disbursed Timestamp
    private Timestamp loanDisbursedTimestamp;  // Disbursed Timestamp

    @Column(nullable = true)  // Optional field
    private String productName;  // Product name (optional)

    private Integer age;  // Age
    private String loanChannel;  // Loan Channel

    @Column(name = "created_at", updatable = false)
    private Timestamp createdAt;  // Created at (autogenerated timestamp)
}
