CREATE TABLE lender_loan_record (
    loan_id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,  -- Loan ID
    lender_name VARCHAR(255),  -- Bank name
    loan_type VARCHAR(255),  -- Loan type
    loan_disbursed_amount NUMERIC,  -- Disbursed amount as a number
    district VARCHAR(255),  -- District
    state VARCHAR(255),  -- State
    branch_code VARCHAR(255),  -- Branch code
    pincode VARCHAR(10),  -- Pincode
    ifsc_code VARCHAR(11),  -- IFSC code
    gender CHAR(1),  -- Gender (M/F/T)
    application_start_timestamp TIMESTAMP,  -- Start Timestamp
    loan_disbursed_timestamp TIMESTAMP,  -- Disbursed Timestamp
    loan_sanction_timestamp TIMESTAMP,
    product_name VARCHAR(255),  -- Product name (optional)
    age INT,  -- Age
    loan_channel VARCHAR(255),  -- Loan Channel
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP  -- Created at (autogenerated timestamp)
);


